iot:
    mqtt:
        auto-reconnect: true
        clean-state: false
        client-id: rachna
        connection-retry: 5
        connection-timeout: 120
        keep-alive: 120
        publish-qos: 0
        publish-topic: home/stack/stmt-req
        status-topic: home/stack/status
        subscribe-qos: 0
        subscribe-topic: home/stack/stmt-res
    secure:
        keystore-file: keystore.jks
        keystore-password: ${KSPASSWORD}
        keystore-type: JKS
        truststore-file: truststore.jks
        truststore-password: ${TSPASSWORD}
management:
    endpoints:
        web:
            exposure:
                include: '*'
server:
    servlet:
        context-path: /proxy
spring:
    application:
        name: rest-proxy
    profiles:
        active: dev,mqtt
web:
    cache-control:
        max-age: 30
